BUNS_NAME = ['Котобулка', 'Delicious', 'Bulochka', 'Хрустящая']
PRICE = [15, 77.5, 12000, 1575, 150.00, 83.1]
INGREDIENT_NAME = ['Вкусный', 'Ochen vkusno', 'Tasty', 'Delicatessen', 'Лакомый', 'Delicacy']
MOCK_BUN_PRICE = 123
MOCK_BUN_NAME = 'Лучшая в мире булка'
MOCK_INGREDIENT_PRICE = 4567
MOCK_INGREDIENT_NAME = 'Совас'
MOCK_INGREDIENT_TYPE = 'Начиночка'
PRICE_BURGER = MOCK_BUN_PRICE * 2 + MOCK_INGREDIENT_PRICE